In [1]:
import pandas as pd
import pickle

# henter vores dataframe (document-term), hvor vores definerede stopwords er sorteret fra
data = pd.read_pickle('dtm_stop.pkl')
data

,aaron,abandon,abandoned,abandoning,abandonment,abhorrent,ability,abject,able,ablebodied,...,young,youre,youth,youthful,youve,zeitchik,zero,zimbabwe,zone,zones
bushjunior,0,1,0,0,0,0,4,0,0,0,...,2,0,0,0,0,0,0,1,0,0
bushsenior,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
carter,0,1,1,0,0,1,2,0,0,0,...,2,0,1,0,0,0,0,0,0,0
clinton,2,0,0,0,0,0,1,0,4,0,...,9,1,0,0,0,0,0,0,0,1
johnson,0,0,0,0,0,0,0,0,10,0,...,2,0,0,0,0,0,0,0,0,0
kennedy,0,1,0,0,1,0,4,0,0,0,...,3,0,2,1,0,0,0,0,0,0
nixon,0,0,0,1,0,0,1,0,4,0,...,2,0,1,0,0,0,1,0,0,0
obama,0,0,0,0,0,0,0,0,1,0,...,3,0,0,0,1,0,0,0,0,0
reagan,0,0,0,0,0,0,0,0,0,0,...,5,0,0,0,0,0,0,0,0,0
trump,0,0,0,0,0,0,0,1,3,0,...,5,0,0,0,0,2,0,0,0,0

In [2]:
from gensim import matutils, models
import scipy.sparse

# For at lave Topic Modeling, skal vi bruge formatet term-document, sÃ¥ vi 'vender' vores df
tdm = data.transpose()
tdm.head()

,bushjunior,bushsenior,carter,clinton,johnson,kennedy,nixon,obama,reagan,trump
aaron,0,0,0,2,0,0,0,0,0,0
abandon,1,0,1,0,0,1,0,0,0,0
abandoned,0,0,1,0,0,0,0,0,0,0
abandoning,0,0,0,0,0,0,1,0,0,0
abandonment,0,0,0,0,0,1,0,0,0,0

In [6]:
# UforstÃ¥elig del - check op pÃ¥ hvad der foregÃ¥r her

# We're going to put the term-document matrix into a new gensim format, from df --> sparse matrix --> gensim corpus
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

<5519x10 sparse matrix of type '<class 'numpy.int64'>'
	with 11903 stored elements in Compressed Sparse Row format>

In [7]:
# Gensim also requires dictionary of the all terms and their respective location in the term-document matrix
cv = pickle.load(open("cv_stop.pkl", "rb"))
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

In [10]:
# Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term),
# we need to specify two other parameters as well - the number of topics and the number of passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=30)
lda.print_topics()

[(0,
  '0.009*"peace" + 0.007*"nations" + 0.005*"soviet" + 0.004*"union" + 0.004*"energy" + 0.004*"free" + 0.004*"great" + 0.003*"defense" + 0.003*"military" + 0.003*"security"'),
 (1,
  '0.005*"work" + 0.004*"children" + 0.003*"future" + 0.003*"government" + 0.003*"economy" + 0.003*"tax" + 0.003*"freedom" + 0.003*"pass" + 0.003*"health" + 0.003*"care"'),
 (2,
  '0.005*"peace" + 0.004*"great" + 0.004*"nations" + 0.004*"budget" + 0.004*"commitments" + 0.004*"vietnam" + 0.004*"act" + 0.003*"increase" + 0.003*"administration" + 0.003*"public"')]